WIP: Migrating Go module to in-toto
in-toto/go-witness pull request #101
Opened 2023-12-13 15:51 UTC by ChaosInTheCRD

This PR is to change the name of the module and all imports inside it to reflect the projects new location at github.com/in-toto/go-witness.

I've tried my best to catch every use of `testifysec/go-witness` but this will probably need some more validation / testing.

2023-12-13 17:09 UTC, ChaosInTheCRD commented
This will fail for now as we are waiting for merging of https://github.com/in-toto/archivista/pull/121

2023-12-13 17:35 UTC, jkjell requested changes
I think we remove the archivista package changes we can hopefully at least get tests running.

2023-12-13 17:35 UTC, jkjell commented on archivista/download.go
> +	archivistaapi "github.com/in-toto/archivista/pkg/api"
Let's move to separate PR

2023-12-13 17:35 UTC, jkjell commented on archivista/searchgitoids.go
> +	archivistaapi "github.com/in-toto/archivista/pkg/api"
move to separate PR

2023-12-13 17:35 UTC, jkjell commented on archivista/store.go
> +	archivistaapi "github.com/in-toto/archivista/pkg/api"
move to separate PR

2023-12-13 17:55 UTC, ChaosInTheCRD commented
So CI is going to continue failing on this PR as the old `archivista-api` module refers to the old `go-witness` module. I suppose this will just wait until https://github.com/in-toto/archivista/pull/121 is merged?

2023-12-14 05:16 UTC, jkjell approved these changes

2023-12-14 16:27 UTC, jkjell approved these changes

2023-12-14 16:50 UTC, ChaosInTheCRD commented
@jkjell just to confirm, the current state is that we are depending on the main branch of https://github.com/in-toto/archivista and we will remove this dependency back to the next release when that is cut?

2023-12-14 17:56 UTC, merged