add jenkins attestor
in-toto/go-witness pull request #323
Opened 2024-08-09 19:17 UTC by joshdabosh

## What this PR does / why we need it
Add a Jenkins build attestor. We can use it in the SLSA provenance data as well, which currently only supports Github Actions and Gitlab CI.

This will allow us to capture data related to a Jenkins build without having to capture the entire scope of environment variables (in case there is sensitive data in the environment).

## Which issue(s) this PR fixes (optional)

Closes #315 

## Acceptance Criteria Met

- [x] Docs changes if needed
- [ ] Testing changes if needed
- [ ] All workflow checks passing (automatically enforced)
- [ ] All review conversations resolved (automatically enforced)
- [ ] [DCO Sign-off](https://github.com/apps/dco)

**Special notes for your reviewer**:

2024-08-11 09:18 UTC, matglas commented
It would be nice to follow conventional commits. This will help to get the change into the changelog too.

2024-08-12 09:23 UTC, joshdabosh commented
Could you clarify what you mean by conventional commits?

2024-08-12 15:00 UTC, matglas commented
You can read up on it here in the contribution doc. https://github.com/in-toto/go-witness/blob/main/CONTRIBUTING.md

2024-08-13 12:48 UTC, jkjell requested changes
This looks great @joshdabosh! Thanks for submitting this. No comments on the current content of the PR but, it would be good to add some tests. If you could add a `jenkins_test.go` for the attestor and add a test case to the [slsa_test.go](https://github.com/in-toto/go-witness/blob/e8606a9b85fb16f78f40bd4fca874bf7fadfd36c/attestation/slsa/slsa_test.go#L131) that should be enough.

2024-08-22 13:01 UTC, jkjell approved these changes
Thanks for the contribution! 🎉 🦉

2024-08-22 13:01 UTC, merged